//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Grades()
        {
            this.Projects = new HashSet<Projects>();
        }
    
        public int id_grade { get; set; }
        public double final_grade { get; set; }
        public double idea_grade { get; set; }
        public double team_grade { get; set; }
        public double innovation_grade { get; set; }
        public double marketing_grade { get; set; }
        public double economy_grade { get; set; }
        public double management_grade { get; set; }
        public double business_plan_grade { get; set; }
        public double presentation_grade { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Projects> Projects { get; set; }
    }
}
