//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projects()
        {
            this.Teams = new HashSet<Teams>();
        }
    
        public int id_project { get; set; }
        public Nullable<int> project_type { get; set; }
        public string project_name { get; set; }
        public System.DateTime date_creation { get; set; }
        public string customer { get; set; }
        public string project_objective { get; set; }
        public string project_tasks { get; set; }
        public string project_problem { get; set; }
        public string project_timeline { get; set; }
        public Nullable<int> prodoct_type { get; set; }
        public string project_relevance { get; set; }
        public string required_resources { get; set; }
        public string target_audience { get; set; }
        public string analogues_competitors { get; set; }
        public string project_novelty { get; set; }
        public string business_plan { get; set; }
        public Nullable<int> achieved_level { get; set; }
        public string final_result { get; set; }
        public string project_logo { get; set; }
        public Nullable<int> project_grades { get; set; }
        public string project_vacancies { get; set; }
    
        public virtual Achieved_levels Achieved_levels { get; set; }
        public virtual Grades Grades { get; set; }
        public virtual Product_types Product_types { get; set; }
        public virtual Project_types Project_types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Teams> Teams { get; set; }
    }
}
