//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teams
    {
        public int id_user { get; set; }
        public int id_project { get; set; }
        public int team_role { get; set; }
        public int application_status { get; set; }
    
        public virtual Application_status Application_status1 { get; set; }
        public virtual Projects Projects { get; set; }
        public virtual Team_roles Team_roles { get; set; }
        public virtual Users Users { get; set; }
    }
}
